openapi: 3.0.0
servers:
  - description: Proxy Server
    url: localhost:8080
info:
  description: Simple Web Cliente
  version: "1.0.0"
  title: Proxy Server
tags:
  - name: Web Client
    description: Web Client
paths:
  '/web':
    post:
      tags:
        - Web Client
      summary: Valores Web Client
      operationId: webClienId
      description: Valores Web Client
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Proxy'
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Proxy'
        description: Pass proxy object
components:
  schemas:
    Proxy:
      type: object
      properties:
        host:
          type: string
          example: localhost
          format: hostname
        port:
          type: integer
          example: 12323
          minimum: 0
          maximum: 65535
        ssl:
          type: boolean
          example: true
        uri:
          type: string
          example: /
